app = 'daily-dad-jokes-ig'
primary_region = 'ams'
kill_signal = 'SIGINT'
kill_timeout = '5s'

[[vm]]
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 512

[mounts]
  source = "data"
  destination = "/mnt"
  processes = ["app"]

[env]
  PERSISTED_VOLUME_PATH = "/mnt"
  PORT = "3000"

[experimental]
allowed_public_ports = [ ]
auto_rollback = true

[[services]]
internal_port = 3000
processes = [ "app" ]
protocol = "tcp"
auto_stop_machines = true
auto_start_machines = true
min_machines_running = 0
script_checks = [ ]

  [[services.ports]]
  handlers = [ "http" ]
  port = 80
  force_https = true

  [[services.ports]]
  handlers = [ "tls", "http" ]
  port = 443
